# Generated by Django 3.2.25 on 2025-04-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReview',
            new_name='Review',
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
